services:
  glpi_app:
    image: sdbrasil/glpi:10.0.17
    container_name: glpi-10
    restart: always
    volumes:
      - /usr/local/glpi/var/marketplace:/usr/share/glpi/marketplace
      - /usr/local/glpi/var/_plugins:/var/lib/glpi/files/_plugins
      - /usr/local/glpi/etc/glpi:/etc/glpi
      - /usr/local/glpi/var/documents:/var/lib/glpi/files/data-documents
      - /usr/local/glpi/var/plugins:/usr/share/glpi/plugins
      - /usr/local/glpi/backup:/backup
      - /usr/local/glpi/log:/var/log/glpi
      - /usr/local/glpi/etc/httpd/glpi.conf:/etc/httpd/conf.d/glpi.conf
      - /usr/local/glpi/etc/httpd/ssl:/etc/httpd/ssl
      - /usr/local/glpi/etc/httpd/modules/mod_ssl.so:/etc/httpd/modules/mod_ssl.so
      - /usr/local/glpi/etc/php.ini:/etc/php.ini
    networks:
      - glpi
    ports:
      - 443:443

  glpidb:
    image: percona/percona-server:8.0
    container_name: db-glpi-10
    networks:
      - glpi
    restart: always
    volumes:
      - /usr/local/percona/log:/var/log/mysql
      - /usr/local/percona/var:/var/lib/mysql
      - /usr/local/percona/backup:/backup
    environment:
      - MYSQL_ROOT_PASSWORD=ADM@MySQL_GLP1
      - MYSQL_DATABASE=glpi
      - MYSQL_USER=glpi
      - MYSQL_PASSWORD=GLP1_MySQL@10
      - TZ=America/Sao_Paulo
    cap_add:
      - SYS_NICE

networks:
  glpi:
    driver: bridge
